let database = [];
database.push("(TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL) (TROLL TROLL TROLL TROLL TROLL)");
database.push("It was a (adjective) and gloomy day. My cat had (verb) away. I slowly walked up the (noun). While I was still in my (noun plural), the bell rang. I went to (verb) it, and who was (verb ending in -ing) at my door? None other than my cat, who was now (emotion). I cried for joy and (verb) him tight, As we head up to bed, and (verb) goodnight.");
database.push("I (verb past tense) this morning at (time), and I did 3 things: (verb past tense), (verb past tense), and (verb past tense) the dogs. Then (pronoun) showered, and got (adjective) in (adjective) clothes. After that (pronoun) got in the (vehicle) and (past tense verb) to (noun). When (pronoun) got there (pronoun) talked with (plural noun). Soon (noun) started. When (pronoun) got to (place) they started watching CNN (number). Soon (pronoun) got (past tense verb) out of the (place).");
database.push("It was a dark and (adjective) night. Paul was (verb-ing) on the coach. (adverb) there was a knock on the door. Paul yelled “(noun) answer the door”. (noun) answered the door. There was a (noun) outside. (noun) yelled “help”, but it was too late. (noun) died. Paul continued (verb-ing) on the coach.");
database.push("In this pamphlet, I will show you how to get rich (adverb):  1. Use your (noun) to make more (noun).  2. Invest in the (adjective) market.  3. Take out (plural noun) from your local bank or financial institution.  4. (verb) your outside spending, focus on business.  5. Put your first (noun) made into a frame.  6. Keep your profits (adjective) in the bank or your safe.  7. Even though family is (adjective), money is more important than anything.  8. Find a credit card with good (nouns).  9. Your are rich, congratulations!");
database.push("In the old creepy (noun) in Durham, (adjective) Carolina, the eccentric mad scientist Dr. von (person in room) worked on his newest invention. As lighting struck, the doctor smiled a/an (adjective) smile. “At last,” he (past tense verb), “the Ultra-Super-Duper (noun) Destroyer® is complete!” He pressed a button on the side of his (noun), and all of a sudden, the horrible machine (adverb) roared to life. As it rose from its (noun), all the doctor’s minions, the obedient  (plural noun), cowered in fear. The machine let out a mighty (sound), but it quickly stopped as the doctor grabbed a/an (adjective) controller and pointed it at his invention. “And now,” he said as he turned a (noun) on his controller, “go and wreak havoc on the city!” The machine turned and (past tense verb) out the door as the doctor laughed (adverb).");
database.push("It was a dark and (adjective) night. I was (verb) through the snow. The snow was (adjective) and soft. My brother was (verb) stew. My (Noun) was (adjective) in the house and (adjective) with my pet Rhino. My Rhinos name is (name).");
database.push("There was a (adjective) cat. This cat was the ruler of (noun) city. The people of the city didn't know the (adjective) cat was the ruler. One day the cat decided to (verb) the people out of the city. The (adjective) people decided they wanted revenge on the (adjective) cat. The (adjective) people (verb) the (adjective) cat. The people tried and tried but the cat was too (adjective). The (adjective) people failed, The cat again took over (noun) city and is ruling to this day.");
database.push("My family and I had to go to the airport. We were moving to (place) for (number) years. We had to hurry, we only had (number) minutes to get ready! I (adverb) (verb) down the stairs. I had to eat leftovers, roasted (animal). We had to get to the airport in a (vehicle). During airport security the guard thought my (noun) was suspicious. Once we got on the plane I realized I forgot my (noun) at home. (person) behind me was (verb ends in ing). I was so (adjective) to finally start taking off. Then I realized that we weren't going to the same place as we wanted to go. We were going to (another place). I was very (adjective) hearing this news. Once we landed I realized that I forgot my (noun). My dad was very (adjective). We all decided to go back home. We were all very (adjective).");
database.push("It was a dark and (adjective) night. The (noun) was (verb) by the candle light. Slowly a (noun) came (adverb) out of the (noun). (adverb) it (verb) towards the (noun). Then the candle went (adjective) on the (noun).");
database.push("It was a dark and (adjective) night. As you (adverb) (verb) into the forest. You hear a (adjective) sound. Then suddenly out jumps a (noun). As you (verb) for your (noun) you (verb) something. Then you (verb) and the (2nd noun from earlier) lay defeated on the (adjective) ground with (adjective) (noun) spilling across the (noun). Then you leave and think (interjection).");
database.push("As you (verb), your teacher (verb ends with s). This perks your (noun). You awaken from your (adjective) (noun). You look at your friend (name). Friend (name from earlier) says “(interjection)” .  Then  you (verb) the (noun). The (last noun) (verb) then the teacher gets in (noun).");
database.push("There are many (adjectives) to choose a/an (noun) to read. First, you could ask for recommendations from friends and (plural noun). Just don't ask aunt (female name) – she only reads (adjectives) books with (article of clothing) on the cover. If your friends and family are no help then use (noun) to search up ideas.");

const a = const b = const c = const d = const e = const n = 10;
